controller_manager:
  ros__parameters:
    update_rate: 40  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_velocity_controller:
      type: ros2_control_mecanum_controller/MecanumVelocityController

mecanum_velocity_controller:
  ros__parameters:
    front_left_wheel_name: "front_left_wheel_joint"
    front_right_wheel_name: "front_right_wheel_joint"
    back_left_wheel_name: "back_left_wheel_joint"
    back_right_wheel_name: "back_right_wheel_joint"

    wheel_separation_lr: 0.3
    wheel_separation_fb: 0.28

    wheel_radius: 0.05

    gearing: 20.0

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    cmd_vel_timeout: 0.5
    use_stamped_vel: false

    publish_rate: 0.01

    odom_frame_id: "odom"
    base_frame_id: "base_link"
    open_loop: false
    enable_odom_tf: false

