teleop_twist_joy_node:
  ros__parameters:
    enable_button: 7
    axis_linear.x: 1
    axis_linear.y: 0
    axis_angular.yaw: 2

    scale_linear.x: 0.5
    scale_linear.y: 0.5
    scale_angular.yaw: 0.5
